//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stamm
    {
        public decimal id { get; set; }
        public Nullable<decimal> brvon { get; set; }
        public Nullable<decimal> clvon { get; set; }
        public Nullable<decimal> hgvon { get; set; }
        public Nullable<decimal> parent { get; set; }
        public string person { get; set; }
        public string anrede { get; set; }
        public string kennung { get; set; }
        public string titel { get; set; }
        public string name { get; set; }
        public string vorname { get; set; }
        public string strasse { get; set; }
        public string plz { get; set; }
        public string ort { get; set; }
        public Nullable<System.DateTime> gebdat { get; set; }
        public Nullable<decimal> gesch { get; set; }
        public string telefon { get; set; }
        public string telefon1 { get; set; }
        public string telefon2 { get; set; }
        public string telefon3 { get; set; }
        public string telefon4 { get; set; }
        public string kasse { get; set; }
        public string kassnum { get; set; }
        public string vers_nr { get; set; }
        public string gruppe { get; set; }
        public Nullable<decimal> svwahl { get; set; }
        public Nullable<decimal> sb { get; set; }
        public string dienstgeb { get; set; }
        public string mname { get; set; }
        public string mvorname { get; set; }
        public string mvers_nr { get; set; }
        public Nullable<System.DateTime> mgebdat { get; set; }
        public Nullable<decimal> mgesch { get; set; }
        public Nullable<System.DateTime> erst_ap { get; set; }
        public Nullable<bool> werbja { get; set; }
        public string mailkenn { get; set; }
        public Nullable<System.DateTime> ersatzdat { get; set; }
        public string beruf { get; set; }
        public byte[] hbem { get; set; }
        public byte[] bbem { get; set; }
        public byte[] cbem { get; set; }
        public string transstat { get; set; }
        public string zugrifftim { get; set; }
        public Nullable<System.DateTime> zugriffdat { get; set; }
        public Nullable<System.DateTime> anlegdat { get; set; }
        public string anlegzeit { get; set; }
        public Nullable<System.DateTime> letztdat { get; set; }
        public Nullable<decimal> userid { get; set; }
        public string staat { get; set; }
        public string vknr { get; set; }
        public string verstat { get; set; }
        public string staterg { get; set; }
        public string expdate { get; set; }
        public Nullable<decimal> allsum { get; set; }
        public string sganrede { get; set; }
        public Nullable<decimal> oldkd_nr { get; set; }
        public Nullable<decimal> oldckd_nr { get; set; }
        public Nullable<decimal> oldhkd_nr { get; set; }
        public string kuncard { get; set; }
        public Nullable<System.DateTime> cletztdat { get; set; }
        public Nullable<System.DateTime> hletztdat { get; set; }
        public Nullable<System.DateTime> besuchdat { get; set; }
        public Nullable<System.DateTime> brersatz { get; set; }
        public Nullable<System.DateTime> hgersatz { get; set; }
        public string blz { get; set; }
        public string ktonr { get; set; }
        public string custbank { get; set; }
        public Nullable<decimal> cat { get; set; }
        public Nullable<decimal> xbmem { get; set; }
        public Nullable<decimal> xcmem { get; set; }
        public Nullable<decimal> xhmem { get; set; }
        public Nullable<decimal> cspkd_nr { get; set; }
        public Nullable<bool> sammel { get; set; }
        public Nullable<decimal> stfil { get; set; }
        public string umsjob { get; set; }
        public Nullable<decimal> opkd_nr { get; set; }
        public string opnr { get; set; }
        public string name2 { get; set; }
        public string strasse2 { get; set; }
        public string mberuf { get; set; }
        public string manrede { get; set; }
        public string mtitel { get; set; }
        public string mdienstgeb { get; set; }
        public string mort { get; set; }
        public string mplz { get; set; }
        public string mstrasse { get; set; }
        public string msgebdat { get; set; }
        public string sgebdat { get; set; }
        public string land { get; set; }
        public Nullable<System.DateTime> sepaseit { get; set; }
        public string indikation { get; set; }
        public string uidnr { get; set; }
        public string hobby { get; set; }
        public string kontoid { get; set; }
        public Nullable<bool> abbu { get; set; }
        public string normtermin { get; set; }
        public string ecinhaber { get; set; }
        public Nullable<bool> zuversich { get; set; }
        public byte[] ibem { get; set; }
        public string bemtext { get; set; }
    }
}

namespace Web_APP.Models.Model1.edmx.Model1.tt
{
    class Model1Entities
    {
    }
}